# Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

# Load the data

In [2]:
data_preprocessed = pd.read_csv(r"C:\Users\Kevin's PC\Desktop\The Data Science Course 2020 - All Resources\df_processed_for_absenteeism.csv")
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Create the Targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# A comment on the targets

In [8]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'], axis=1)

In [10]:
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
unscaled_inputs = data_with_targets.iloc[:,0:-1]  # [:,0:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

# standardize the data

In [14]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean = None
        self.var = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
# columns_to_scale = [ 'Month Value',
#        'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\ana\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:71: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [20]:
absenteeism_scaler.fit(unscaled_inputs)

C:\ana\envs\tensorflow\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

# Split the data into train & test and shuffle

In [23]:
from sklearn.model_selection import train_test_split

# split

In [24]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 684         0         0         0         1     1.228426   
 489         0         0         0         1     0.330204   
 498         0         0         0         1    -0.568019   
 117         0         0         0         1    -0.268611   
 325         0         0         0         0     1.228426   
 ..        ...       ...       ...       ...          ...   
 599         0         0         0         1    -1.466241   
 111         0         0         1         0     1.527833   
 308         0         0         0         1     0.929019   
 22          1         0         0         0     0.929019   
 226         0         0         0         1    -0.268611   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 684               -0.654143 -1.006686        -1.819793          1 -0.919030   
 489                1.624567 -1.320435        -0.408580          1 -0.919030   
 498               -1.0163

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.75, random_state = 8)

In [26]:
print(x_train.shape, y_train.shape)

(525, 11) (525,)


In [27]:
print(x_test.shape, y_test.shape)

(175, 11) (175,)


# Logistic regression with sklearn

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Training the model

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
reg.score(x_train, y_train)

0.7771428571428571

# Manually check the accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,

In [33]:
y_train

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,

In [35]:
np.sum((model_outputs==y_train))

408

In [36]:
model_outputs.shape[0]

525

In [37]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7771428571428571

# Finding the intercept and coefficient

In [38]:
reg.intercept_

array([-1.70027959])

In [39]:
reg.coef_

array([[ 2.79889952,  0.87062049,  3.00142769,  0.93714554,  0.03730825,
         0.59816101, -0.26869177,  0.28590263, -0.1083608 ,  0.51758959,
        -0.29578411]])

In [40]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.798900
1                 Reason_2     0.870620
2                 Reason_3     3.001428
3                 Reason_4     0.937146
4              Month Value     0.037308
5   Transportation Expense     0.598161
6                      Age    -0.268692
7          Body Mass Index     0.285903
8                Education    -0.108361
9                 Children     0.517590
10                    Pets    -0.295784

In [43]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.700280
1                 Reason_1     2.798900
2                 Reason_2     0.870620
3                 Reason_3     3.001428
4                 Reason_4     0.937146
5              Month Value     0.037308
6   Transportation Expense     0.598161
7                      Age    -0.268692
8          Body Mass Index     0.285903
9                Education    -0.108361
10                Children     0.517590
11                    Pets    -0.295784

In [44]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [45]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.700280    0.182632
1                 Reason_1     2.798900   16.426560
2                 Reason_2     0.870620    2.388392
3                 Reason_3     3.001428   20.114233
4                 Reason_4     0.937146    2.552684
5              Month Value     0.037308    1.038013
6   Transportation Expense     0.598161    1.818771
7                      Age    -0.268692    0.764379
8          Body Mass Index     0.285903    1.330963
9                Education    -0.108361    0.897304
10                Children     0.517590    1.677978
11                    Pets    -0.295784    0.743948

In [46]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.001428   20.114233
1                 Reason_1     2.798900   16.426560
4                 Reason_4     0.937146    2.552684
2                 Reason_2     0.870620    2.388392
6   Transportation Expense     0.598161    1.818771
10                Children     0.517590    1.677978
8          Body Mass Index     0.285903    1.330963
5              Month Value     0.037308    1.038013
9                Education    -0.108361    0.897304
7                      Age    -0.268692    0.764379
11                    Pets    -0.295784    0.743948
0                Intercept    -1.700280    0.182632

# Testing the model

In [47]:
reg.score(x_test,y_test)

0.7542857142857143

In [48]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.8324614 , 0.1675386 ],
       [0.7062053 , 0.2937947 ],
       [0.30135327, 0.69864673],
       [0.27919711, 0.72080289],
       [0.78610628, 0.21389372],
       [0.35906478, 0.64093522],
       [0.7015488 , 0.2984512 ],
       [0.25685554, 0.74314446],
       [0.28559182, 0.71440818],
       [0.17370917, 0.82629083],
       [0.05910731, 0.94089269],
       [0.23153248, 0.76846752],
       [0.77266487, 0.22733513],
       [0.47379345, 0.52620655],
       [0.5027943 , 0.4972057 ],
       [0.2991405 , 0.7008595 ],
       [0.7199164 , 0.2800836 ],
       [0.80268124, 0.19731876],
       [0.24017149, 0.75982851],
       [0.12851277, 0.87148723],
       [0.49647926, 0.50352074],
       [0.20027252, 0.79972748],
       [0.34901   , 0.65099   ],
       [0.57496661, 0.42503339],
       [0.87487902, 0.12512098],
       [0.86628871, 0.13371129],
       [0.77914676, 0.22085324],
       [0.7667248 , 0.2332752 ],
       [0.7667248 , 0.2332752 ],
       [0.06099875, 0.93900125],
       [0.

In [50]:
predicted_proba.shape

(175, 2)

In [51]:
predicted_proba[:,1]

array([0.1675386 , 0.2937947 , 0.69864673, 0.72080289, 0.21389372,
       0.64093522, 0.2984512 , 0.74314446, 0.71440818, 0.82629083,
       0.94089269, 0.76846752, 0.22733513, 0.52620655, 0.4972057 ,
       0.7008595 , 0.2800836 , 0.19731876, 0.75982851, 0.87148723,
       0.50352074, 0.79972748, 0.65099   , 0.42503339, 0.12512098,
       0.13371129, 0.22085324, 0.2332752 , 0.2332752 , 0.93900125,
       0.64930669, 0.14284986, 0.21389372, 0.34027345, 0.63906577,
       0.12390332, 0.85847578, 0.73025163, 0.13879427, 0.69549194,
       0.38821508, 0.22150261, 0.50558321, 0.83416827, 0.37242127,
       0.52063368, 0.93362211, 0.51747663, 0.2937947 , 0.71894442,
       0.28760034, 0.87218451, 0.72119601, 0.62520257, 0.11796677,
       0.30792534, 0.22537899, 0.76424351, 0.74314446, 0.27560109,
       0.2984512 , 0.23527906, 0.94332919, 0.49772894, 0.8703087 ,
       0.7836806 , 0.2984512 , 0.73479309, 0.2332752 , 0.51674754,
       0.43050195, 0.13632032, 0.70769096, 0.23128325, 0.12883